# Somerville Data Pipeline configurations
# This is a sample config. Add items to keys and change name to `config.yaml`

# SFTP credentials
sftp_server: ''
sftp_user: ''
sftp_pass: ''
sftp_port: ''
sftp_remote_dir: ''

# QAlert
qscend_key: ''
qscend_url: ''
