# Somerville Data Pipeline auth keys
# This is a sample Auth config. Add items to keys and change name to `auth.yaml`

# SFTP credentials
sftp_server: ''
sftp_user: ''
sftp_pass: ''
sftp_port: ''
sftp_remote_dir: ''

# QAlert / QScend API
qscend_key: ''
qscend_url: ''
