# Somerville Data Pipeline auth keys
# This is a sample auth secrets config file. 
# Add items to keys and change name to `auth.yaml`

# SFTP credentials
sftp_server: ''
sftp_user: ''
sftp_pass: ''
sftp_port: ''
sftp_remote_dir: ''

# QAlert / QScend API
qscend_key: ''
qscend_url: ''

# Socrata Client
socrata_username: ''
socrata_password: ''
socrata_token: ''
socrata_url: ''
